name: studybuddy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.4.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  google_fonts: ^6.3.1
  flutter_spinkit: ^5.2.2
  flutter_animate: ^4.5.2
  google_sign_in: ^5.4.0
  intl: ^0.20.2
  flutter_markdown_plus: ^1.0.5
  flutter_highlight: ^0.7.0
  google_generative_ai: ^0.4.7
  multi_select_flutter: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # The following line ensures that the Material Icons font is included with your application.
  uses-material-design: true

  # To add assets to your application, add an assets section like this:
  assets:
    - assets/google_logo.png
    - assets/apple_logo.png
